# Задача 2, лист 7

In [30]:
import pandas as pd
import numpy as np
import statsmodels.api as sm 
import statsmodels.formula.api as smf
from statsmodels.iolib.summary2 import summary_params # вывод результатов тестирования
from statsmodels.iolib.summary2 import summary_col # вывод результатов тестирования
from statsmodels.stats.outliers_influence import variance_inflation_factor # VIF
import scipy
import matplotlib.pyplot as plt
import seaborn as sns
import re
import scipy.stats as stats

In [161]:
data_string='''totwrk                       -0.167***         
                              (0.018)          
                                               
age                           -6.255           
                             (11.191)          
                                               
I(age2)                        0.109           
                              (0.134)          
                                               
south                       114.547***         
                             (40.637)          
                                               
male                         90.457***         
                             (34.257)          
                                               
Constant                    3613.995***        
                             (218.433)  '''

In [188]:
date_lst=re.findall(r'([-+]?\d+.\d+)', data_string)
date_lst

['-0.167',
 '0.018',
 '-6.255',
 '11.191',
 '0.109',
 '0.134',
 '114.547',
 '40.637',
 '90.457',
 '34.257',
 '3613.995',
 '218.433']

In [189]:
beta = np.reshape(date_lst, (6,2)) # делаем двумерный массив, 2 столбца и 6 строк
beta

array([['-0.167', '0.018'],
       ['-6.255', '11.191'],
       ['0.109', '0.134'],
       ['114.547', '40.637'],
       ['90.457', '34.257'],
       ['3613.995', '218.433']], dtype='<U8')

In [190]:
beta[:,0]

array(['-0.167', '-6.255', '0.109', '114.547', '90.457', '3613.995'],
      dtype='<U8')

In [191]:
beta = beta[:,0].astype(float)
beta

array([-1.670000e-01, -6.255000e+00,  1.090000e-01,  1.145470e+02,
        9.045700e+01,  3.613995e+03])

In [203]:
empiric='''  totwrk age south male
1  2160  32    1    0  
2  1720  24    0    1  
3  2390  44    0    1 '''

In [204]:
X = re.findall(r'([-+]?\d+)', empiric)
X

['1',
 '2160',
 '32',
 '1',
 '0',
 '2',
 '1720',
 '24',
 '0',
 '1',
 '3',
 '2390',
 '44',
 '0',
 '1']

In [205]:
X = np.reshape(X, (3,5))
X

array([['1', '2160', '32', '1', '0'],
       ['2', '1720', '24', '0', '1'],
       ['3', '2390', '44', '0', '1']], dtype='<U4')

In [206]:
X=np.delete(X, 0, 1) # удаляем нулевой столбец, 1 - в строке
X

array([['2160', '32', '1', '0'],
       ['1720', '24', '0', '1'],
       ['2390', '44', '0', '1']], dtype='<U4')

In [208]:
X = np.c_[X, np.ones(3)] #np.ones - массив единиц размерности (три)
X
# здесь я добавляю еще один столбец единичек (const). Так как впоследствии из-за несоответствия размерности матриц они не перемножаются

array([['2160', '32', '1', '0', '1.0', '1.0'],
       ['1720', '24', '0', '1', '1.0', '1.0'],
       ['2390', '44', '0', '1', '1.0', '1.0']], dtype='<U32')

In [209]:
beta=beta.astype(float)
X=X.astype(float)

In [210]:
beta

array([-1.670000e-01, -6.255000e+00,  1.090000e-01,  1.145470e+02,
        9.045700e+01,  3.613995e+03])

In [211]:
X

array([[2.16e+03, 3.20e+01, 1.00e+00, 0.00e+00, 1.00e+00, 1.00e+00],
       [1.72e+03, 2.40e+01, 0.00e+00, 1.00e+00, 1.00e+00, 1.00e+00],
       [2.39e+03, 4.40e+01, 0.00e+00, 1.00e+00, 1.00e+00, 1.00e+00]])

In [212]:
X@beta
# Если добавить лишь один столбец единичек (const) в матрицу X, то матрицы не перемножатся.
# Правильно ли добавлять еще один столбец единичек? Если да, то ответы не сходятся :(

array([3143.681, 3381.639, 3144.649])

# Задача 3, листок 7

In [213]:
date_string='''age                          0.021***          
                              (0.004)          
                                               
IQ                           0.008***          
                              (0.001)          
                                               
south                        -0.099***         
                              (0.027)          
                                               
married                      0.201***          
                              (0.040)          
                                               
urban                        0.175***          
                              (0.028)          
                                               
Constant                     4.974***          
                              (0.165)    '''

In [214]:
date_lst=re.findall(r'([-+]?\d+.\d+)', date_string)
date_lst

['0.021',
 '0.004',
 '0.008',
 '0.001',
 '-0.099',
 '0.027',
 '0.201',
 '0.040',
 '0.175',
 '0.028',
 '4.974',
 '0.165']

In [215]:
beta = np.reshape(date_lst, (6,2)) # делаем двумерный массив, 2 столбца и 6 строк
beta

array([['0.021', '0.004'],
       ['0.008', '0.001'],
       ['-0.099', '0.027'],
       ['0.201', '0.040'],
       ['0.175', '0.028'],
       ['4.974', '0.165']], dtype='<U6')

In [216]:
beta[:,0]

array(['0.021', '0.008', '-0.099', '0.201', '0.175', '4.974'], dtype='<U6')

In [217]:
beta = beta[:,0].astype(float)
beta

array([ 0.021,  0.008, -0.099,  0.201,  0.175,  4.974])

In [218]:
empiric='''  age IQ  south married urban
1 36  105   1      1      1  
2 29  123   0      1      0  
3 25  112   1      0      1  '''

In [219]:
X=re.findall(r'([-+]?\d+)', empiric)
X

['1',
 '36',
 '105',
 '1',
 '1',
 '1',
 '2',
 '29',
 '123',
 '0',
 '1',
 '0',
 '3',
 '25',
 '112',
 '1',
 '0',
 '1']

In [220]:
X = np.reshape(X, (3,6))
X

array([['1', '36', '105', '1', '1', '1'],
       ['2', '29', '123', '0', '1', '0'],
       ['3', '25', '112', '1', '0', '1']], dtype='<U3')

In [221]:
X=np.delete(X, 0, 1) # удаляем нулевой столбец, 1 - в строке
X

array([['36', '105', '1', '1', '1'],
       ['29', '123', '0', '1', '0'],
       ['25', '112', '1', '0', '1']], dtype='<U3')

In [222]:
X = np.c_[X, np.ones(3)] #np,ones - массив единиц размерности (три)
X

array([['36', '105', '1', '1', '1', '1.0'],
       ['29', '123', '0', '1', '0', '1.0'],
       ['25', '112', '1', '0', '1', '1.0']], dtype='<U32')

In [223]:
beta=beta.astype(float)
X=X.astype(float)

In [225]:
X@beta
# Вся размерность совпала, однако ответы не совпадают с ответами НВ

array([6.847, 6.768, 6.471])

# Задача 4, листок 7

In [226]:
date_string='''exper                        0.037***          
                              (0.006)          
                                               
I(exper2)                    -0.001***         
                             (0.0001)          
                                               
female                       -0.363***         
                              (0.040)          
                                               
married                      0.144***          
                              (0.045)          
                                               
smsa                         0.273***          
                              (0.044)          
                                               
Constant                     1.250***          
                              (0.061)  '''

In [227]:
date_lst=re.findall(r'([-+]?\d+.\d+)', date_string)
date_lst

['0.037',
 '0.006',
 '-0.001',
 '0.0001',
 '-0.363',
 '0.040',
 '0.144',
 '0.045',
 '0.273',
 '0.044',
 '1.250',
 '0.061']

In [228]:
beta = np.reshape(date_lst, (6,2))
beta

array([['0.037', '0.006'],
       ['-0.001', '0.0001'],
       ['-0.363', '0.040'],
       ['0.144', '0.045'],
       ['0.273', '0.044'],
       ['1.250', '0.061']], dtype='<U6')

In [229]:
beta = beta[:,0].astype(float)
beta

array([ 3.70e-02, -1.00e-03, -3.63e-01,  1.44e-01,  2.73e-01,  1.25e+00])

In [230]:
empiric='''  exper female married smsa
1   5     1       1     1  
2  26     0       0     1  
3  38     1       1     0  '''

In [231]:
X=re.findall(r'([-+]?\d+)', empiric)
X

['1', '5', '1', '1', '1', '2', '26', '0', '0', '1', '3', '38', '1', '1', '0']

In [232]:
X = np.reshape(X, (3,5)) # делаем двумерный массив
X

array([['1', '5', '1', '1', '1'],
       ['2', '26', '0', '0', '1'],
       ['3', '38', '1', '1', '0']], dtype='<U2')

In [233]:
X=np.delete(X, 0, 1)
X

array([['5', '1', '1', '1'],
       ['26', '0', '0', '1'],
       ['38', '1', '1', '0']], dtype='<U2')

In [235]:
X = np.c_[X, np.ones(3)] #np,ones - массив единиц размерности (три)
X

array([['5', '1', '1', '1', '1.0', '1.0'],
       ['26', '0', '0', '1', '1.0', '1.0'],
       ['38', '1', '1', '0', '1.0', '1.0']], dtype='<U32')

In [236]:
beta=beta.astype(float)
X=X.astype(float)

In [238]:
X@beta
# тот же вопрос, что и в задаче 2

array([1.488, 2.629, 2.565])

# Задача 5, листок 7

In [249]:
date_string='''log(capital)                 0.208***          
                              (0.017)          
                                               
log(labour)                  0.715***          
                              (0.023)          
                                               
Constant                     -1.711***         
                              (0.097)  '''

In [250]:
date_lst=re.findall(r'([-+]?\d+.\d+)', date_string)
date_lst

['0.208', '0.017', '0.715', '0.023', '-1.711', '0.097']

In [251]:
beta = np.reshape(date_lst, (2,3))
beta

array([['0.208', '0.017', '0.715'],
       ['0.023', '-1.711', '0.097']], dtype='<U6')

In [252]:
beta = beta[:,0].astype(float)
beta

array([0.208, 0.023])

In [291]:
empiric='''  capital labour
1  2.970 85  
2  10.450  60  
3  3.850  105  '''

In [296]:
X=re.findall(r'([-+]?\d+.\d+|[-+]?\d+)', empiric)
X

['1', '2.970', '85', '2', '10.450', '60', '3', '3.850', '105']

In [297]:
X = np.reshape(X, (3,3)) # делаем двумерный массив
X

array([['1', '2.970', '85'],
       ['2', '10.450', '60'],
       ['3', '3.850', '105']], dtype='<U6')

In [298]:
X=np.delete(X, 0, 1)
X

array([['2.970', '85'],
       ['10.450', '60'],
       ['3.850', '105']], dtype='<U6')

In [299]:
beta=beta.astype(float)
X=X.astype(float)

In [300]:
X@beta

array([2.57276, 3.5536 , 3.2158 ])

# Задача 6, листок 7

In [301]:
date_string='''log(capital)                 0.183***          
                              (0.017)          
                                               
log(labour)                  0.515***          
                              (0.083)          
                                               
I(log(capital)2)             0.023***          
                              (0.005)          
                                               
I(log(labour)2)               0.020**          
                              (0.010)          
                                               
Constant                     -1.304***         
                              (0.189) '''

In [302]:
date_lst=re.findall(r'([-+]?\d+.\d+)', date_string)
date_lst

['0.183',
 '0.017',
 '0.515',
 '0.083',
 '0.023',
 '0.005',
 '0.020',
 '0.010',
 '-1.304',
 '0.189']

In [303]:
beta = np.reshape(date_lst, (5,2))
beta

array([['0.183', '0.017'],
       ['0.515', '0.083'],
       ['0.023', '0.005'],
       ['0.020', '0.010'],
       ['-1.304', '0.189']], dtype='<U6')

In [304]:
beta = beta[:,0].astype(float)
beta

array([ 0.183,  0.515,  0.023,  0.02 , -1.304])

In [307]:
empiric='''  capital labour
1  22.140   407  
2  7.320   197  
3  0.670    31  '''

In [308]:
X=re.findall(r'([-+]?\d+.\d+|[-+]?\d+)', empiric)
X

['1', '22.140', '407', '2', '7.320', '197', '3', '0.670', '31']

In [309]:
X = np.reshape(X, (3,3)) # делаем двумерный массив
X

array([['1', '22.140', '407'],
       ['2', '7.320', '197'],
       ['3', '0.670', '31']], dtype='<U6')

In [310]:
X=np.delete(X, 0, 1)
X

array([['22.140', '407'],
       ['7.320', '197'],
       ['0.670', '31']], dtype='<U6')

In [314]:
X = np.c_[X, np.ones(3)] #np,ones - массив единиц размерности (три)
X

array([['22.140', '407', '1.0', '1.0', '1.0'],
       ['7.320', '197', '1.0', '1.0', '1.0'],
       ['0.670', '31', '1.0', '1.0', '1.0']], dtype='<U32')

In [315]:
beta=beta.astype(float)
X=X.astype(float)

In [317]:
X@beta

array([212.39562, 101.53356,  14.82661])

# Задача 1.2, листок 8

In [35]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/sleep75.csv')
df['totwrk2_10000'] = df['totwrk']**2/10000
df

age  black  case  clerical  construc  educ  earns74  gdhlth  inlf  leis1  \
0     32      0     1  0.000000  0.000000    12        0       0     1   3529   
1     31      0     2  0.000000  0.000000    14     9500       1     1   2140   
2     44      0     3  0.000000  0.000000    17    42500       1     1   4595   
3     30      0     4  0.000000  0.000000    12    42500       1     1   3211   
4     64      0     5  0.000000  0.000000    14     2500       1     1   4052   
..   ...    ...   ...       ...       ...   ...      ...     ...   ...    ...   
701   45      0   702  0.182331  0.030075    12     5500       1     0   5069   
702   34      0   703  0.182331  0.030075    10     2500       0     0   5885   
703   37      0   704  0.182331  0.030075    12     3500       1     0   4719   
704   54      0   705  0.182331  0.030075    17    32500       1     0   5149   
705   30      0   706  0.182331  0.030075    16     6750       1     0   4747   

     ...  totwrk  union  worknrm  workscnd  exper  yngkid  yrsmarr     hrwage  \
0    ...    3438      0     3438         0     14       0       13   7.070004   
1    ...    5020      0     5020         0     11       0        0   1.429999   
2    ...    2815      0     2815         0     21       0        0  20.529997   
3    ...    3786      0     3786         0     12       0       12   9.619998   
4    ...    2580      0     2580         0     44       0       33   2.750000   
..   ...     ...    ...      ...       ...    ...     ...      ...        ...   
701  ...    2026      0     2026         0     27       0       18        NaN   
702  ...     675      1      465       210     18       0        4        NaN   
703  ...    1851      0     1851         0     19       0       17        NaN   
704  ...    1961      1     1481       480     31       0       22        NaN   
705  ...    2363      0     2363         0      8       1        9        NaN   

     agesq  totwrk2_10000  
0     1024      1181.9844  
1      961      2520.0400  
2     1936       792.4225  
3      900      1433.3796  
4     4096       665.6400  
..     ...            ...  
701   2025       410.4676  
702   1156        45.5625  
703   1369       342.6201  
704   2916       384.5521  
705    900       558.3769  

[706 rows x 35 columns]

In [36]:
models = smf.ols(formula = 'sleep~I(totwrk/100)+I(totwrk**2/10000)+age+smsa+male', data = df).fit()
models.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sleep   R-squared:                       0.128
Model:                            OLS   Adj. R-squared:                  0.122
Method:                 Least Squares   F-statistic:                     20.57
Date:                Sun, 16 Apr 2023   Prob (F-statistic):           3.42e-19
Time:                        10:26:41   Log-Likelihood:                -5257.2
No. Observations:                 706   AIC:                         1.053e+04
Df Residuals:                     700   BIC:                         1.055e+04
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept               3428.8048     76.655     44.730      0.000    3278.303    3579.306
I(totwrk / 100)           -8.1953      4.789     -1.711      0.088     -17.599       1.208
I(totwrk ** 2 / 10000)    -0.2142      0.111     -1.930      0.054      -0.432       0.004
age                        2.8167      1.387      2.031      0.043       0.094       5.540
smsa                     -78.0495     32.072     -2.434      0.015    -141.019     -15.080
male                      86.6388     34.200      2.533      0.012      19.492     153.786
==============================================================================
Omnibus:                       63.342   Durbin-Watson:                   1.947
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              177.146
Skew:                          -0.442   Prob(JB):                     3.41e-39
Kurtosis:                       5.289   Cond. No.                     3.32e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [43]:
models.f_test('I(totwrk/100)=I(totwrk**2/10000)')

PatsyError: unrecognized token in constraint
    I(totwrk/100)=I(totwrk**2/10000)
    ^

# Задача 2.1, листок 8

In [51]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/sleep75.csv')
df['age_2']=df['age']*df['age']
df

age  black  case  clerical  construc  educ  earns74  gdhlth  inlf  leis1  \
0     32      0     1  0.000000  0.000000    12        0       0     1   3529   
1     31      0     2  0.000000  0.000000    14     9500       1     1   2140   
2     44      0     3  0.000000  0.000000    17    42500       1     1   4595   
3     30      0     4  0.000000  0.000000    12    42500       1     1   3211   
4     64      0     5  0.000000  0.000000    14     2500       1     1   4052   
..   ...    ...   ...       ...       ...   ...      ...     ...   ...    ...   
701   45      0   702  0.182331  0.030075    12     5500       1     0   5069   
702   34      0   703  0.182331  0.030075    10     2500       0     0   5885   
703   37      0   704  0.182331  0.030075    12     3500       1     0   4719   
704   54      0   705  0.182331  0.030075    17    32500       1     0   5149   
705   30      0   706  0.182331  0.030075    16     6750       1     0   4747   

     ...  totwrk  union  worknrm  workscnd  exper  yngkid  yrsmarr     hrwage  \
0    ...    3438      0     3438         0     14       0       13   7.070004   
1    ...    5020      0     5020         0     11       0        0   1.429999   
2    ...    2815      0     2815         0     21       0        0  20.529997   
3    ...    3786      0     3786         0     12       0       12   9.619998   
4    ...    2580      0     2580         0     44       0       33   2.750000   
..   ...     ...    ...      ...       ...    ...     ...      ...        ...   
701  ...    2026      0     2026         0     27       0       18        NaN   
702  ...     675      1      465       210     18       0        4        NaN   
703  ...    1851      0     1851         0     19       0       17        NaN   
704  ...    1961      1     1481       480     31       0       22        NaN   
705  ...    2363      0     2363         0      8       1        9        NaN   

     agesq  age_2  
0     1024   1024  
1      961    961  
2     1936   1936  
3      900    900  
4     4096   4096  
..     ...    ...  
701   2025   2025  
702   1156   1156  
703   1369   1369  
704   2916   2916  
705    900    900  

[706 rows x 35 columns]

In [52]:
model = smf.ols(data = df , formula = 'sleep~totwrk +  age + +age_2+ smsa + male + south').fit()
model_1 = smf.ols(data = df , formula = 'age_2~totwrk +  age + smsa + male + south').fit()
model_2 = smf.ols(data = df , formula = 'male~totwrk+  age+age_2 + smsa  + south').fit()
model_3 = smf.ols(data = df , formula = 'age~totwrk+  age + smsa +male + south').fit()
model_1.params.round(3)

Intercept   -1552.146
totwrk         -0.019
age            83.036
smsa           -0.555
male            2.636
south          17.250
dtype: float64

In [54]:
model_1.rsquared

0.9847552819309748

In [63]:
VIF_1 = 1/(1 - round(model_1.rsquared,3))
VIF_1.round(2)

66.67

In [64]:
VIF_2 = 1/(1 - round(model_2.rsquared,3))
VIF_2.round(2)

1.17

In [68]:
model_3.rsquared # снизу не будет делиться на ноль!

1.0

In [69]:
VIF_3 = 1/(1 - model_3.rsquared)
VIF_3.round(2)

C:\Users\Stepan\AppData\Local\Temp\ipykernel_13040\2082198633.py:1: RuntimeWarning: divide by zero encountered in double_scalars
  VIF_3 = 1/(1 - model_3.rsquared)


inf

# Задача 3.1, листок 8

In [73]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/sleep75.csv')
df

age  black  case  clerical  construc  educ  earns74  gdhlth  inlf  leis1  \
0     32      0     1  0.000000  0.000000    12        0       0     1   3529   
1     31      0     2  0.000000  0.000000    14     9500       1     1   2140   
2     44      0     3  0.000000  0.000000    17    42500       1     1   4595   
3     30      0     4  0.000000  0.000000    12    42500       1     1   3211   
4     64      0     5  0.000000  0.000000    14     2500       1     1   4052   
..   ...    ...   ...       ...       ...   ...      ...     ...   ...    ...   
701   45      0   702  0.182331  0.030075    12     5500       1     0   5069   
702   34      0   703  0.182331  0.030075    10     2500       0     0   5885   
703   37      0   704  0.182331  0.030075    12     3500       1     0   4719   
704   54      0   705  0.182331  0.030075    17    32500       1     0   5149   
705   30      0   706  0.182331  0.030075    16     6750       1     0   4747   

     ...  spwrk75  totwrk  union  worknrm  workscnd  exper  yngkid  yrsmarr  \
0    ...        0    3438      0     3438         0     14       0       13   
1    ...        0    5020      0     5020         0     11       0        0   
2    ...        1    2815      0     2815         0     21       0        0   
3    ...        1    3786      0     3786         0     12       0       12   
4    ...        1    2580      0     2580         0     44       0       33   
..   ...      ...     ...    ...      ...       ...    ...     ...      ...   
701  ...        1    2026      0     2026         0     27       0       18   
702  ...        0     675      1      465       210     18       0        4   
703  ...        1    1851      0     1851         0     19       0       17   
704  ...        1    1961      1     1481       480     31       0       22   
705  ...        0    2363      0     2363         0      8       1        9   

        hrwage  agesq  
0     7.070004   1024  
1     1.429999    961  
2    20.529997   1936  
3     9.619998    900  
4     2.750000   4096  
..         ...    ...  
701        NaN   2025  
702        NaN   1156  
703        NaN   1369  
704        NaN   2916  
705        NaN    900  

[706 rows x 34 columns]

In [78]:
df['totwrk_south'] = df['totwrk'] * df['south']
df

age  black  case  clerical  construc  educ  earns74  gdhlth  inlf  leis1  \
0     32      0     1  0.000000  0.000000    12        0       0     1   3529   
1     31      0     2  0.000000  0.000000    14     9500       1     1   2140   
2     44      0     3  0.000000  0.000000    17    42500       1     1   4595   
3     30      0     4  0.000000  0.000000    12    42500       1     1   3211   
4     64      0     5  0.000000  0.000000    14     2500       1     1   4052   
..   ...    ...   ...       ...       ...   ...      ...     ...   ...    ...   
701   45      0   702  0.182331  0.030075    12     5500       1     0   5069   
702   34      0   703  0.182331  0.030075    10     2500       0     0   5885   
703   37      0   704  0.182331  0.030075    12     3500       1     0   4719   
704   54      0   705  0.182331  0.030075    17    32500       1     0   5149   
705   30      0   706  0.182331  0.030075    16     6750       1     0   4747   

     ...  union  worknrm  workscnd  exper  yngkid  yrsmarr     hrwage  agesq  \
0    ...      0     3438         0     14       0       13   7.070004   1024   
1    ...      0     5020         0     11       0        0   1.429999    961   
2    ...      0     2815         0     21       0        0  20.529997   1936   
3    ...      0     3786         0     12       0       12   9.619998    900   
4    ...      0     2580         0     44       0       33   2.750000   4096   
..   ...    ...      ...       ...    ...     ...      ...        ...    ...   
701  ...      0     2026         0     27       0       18        NaN   2025   
702  ...      1      465       210     18       0        4        NaN   1156   
703  ...      0     1851         0     19       0       17        NaN   1369   
704  ...      1     1481       480     31       0       22        NaN   2916   
705  ...      0     2363         0      8       1        9        NaN    900   

     totwrk_south_interaction  totwrk_south  
0                           0             0  
1                        5020          5020  
2                           0             0  
3                           0             0  
4                           0             0  
..                        ...           ...  
701                         0             0  
702                         0             0  
703                         0             0  
704                      1961          1961  
705                      2363          2363  

[706 rows x 36 columns]

In [79]:
model = smf.ols(data = df , formula = 'sleep ~ totwrk+south+totwrk_south+age+male+smsa').fit()
model_1 = smf.ols(data = df , formula = 'totwrk ~ south+totwrk_south+age+male+smsa').fit()
model_2 = smf.ols(data = df , formula = 'south ~ totwrk+totwrk_south+age+male+smsa').fit()
model_3 = smf.ols(data = df , formula = 'totwrk_south ~ totwrk+south+age+male+smsa').fit()
model_1.params.round(3)

Intercept       1883.936
south          -1780.732
totwrk_south       0.862
age               -3.438
male             645.996
smsa             -46.641
dtype: float64

In [80]:
VIF_1 = 1/(1 - round(model_1.rsquared,3))
VIF_1.round(2)

1.32

In [81]:
VIF_2 = 1/(1 - round(model_2.rsquared,3))
VIF_2.round(2)

8.55

In [84]:
VIF_3 = 1/(1 - round(model_3.rsquared,3))
VIF_3.round(2)

8.77

# Задача 4.1, листок 8

In [85]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/wage2.csv')
df

wage  hours   IQ  KWW  educ  exper  tenure  age  married  black  south  \
0     769     40   93   35    12     11       2   31        1      0      0   
1     808     50  119   41    18     11      16   37        1      0      0   
2     825     40  108   46    14     11       9   33        1      0      0   
3     650     40   96   32    12     13       7   32        1      0      0   
4     562     40   74   27    11     14       5   34        1      0      0   
..    ...    ...  ...  ...   ...    ...     ...  ...      ...    ...    ...   
930   520     40   79   28    16      6       1   30        1      1      1   
931  1202     40  102   32    13     10       3   31        1      0      1   
932   538     45   77   22    12     12      10   28        1      1      1   
933   873     44  109   25    12     12      12   28        1      0      1   
934  1000     40  107   32    12     17      18   35        1      0      1   

     urban  sibs  brthord  meduc  feduc     lwage  
0        1     1      2.0    8.0    8.0  6.645091  
1        1     1      NaN   14.0   14.0  6.694562  
2        1     1      2.0   14.0   14.0  6.715384  
3        1     4      3.0   12.0   12.0  6.476973  
4        1    10      6.0    6.0   11.0  6.331502  
..     ...   ...      ...    ...    ...       ...  
930      0     0      1.0   11.0    NaN  6.253829  
931      1     7      7.0    8.0    6.0  7.091742  
932      0     9      NaN    7.0    NaN  6.287858  
933      0     1      1.0    NaN   11.0  6.771935  
934      0     5      1.0    NaN    NaN  6.907755  

[935 rows x 17 columns]

In [86]:
model = smf.ols(data = df , formula = 'np.log(wage) ~ age+ I(age**2)+ IQ+ married+ south+ urban').fit()

In [87]:
model_1 = smf.ols(data = df , formula = 'age ~ I(age**2)+ IQ+married+south+urban').fit()
model_2 = smf.ols(data = df , formula = 'I(age**2) ~ age+ IQ+married+south+urban').fit()
model_3 = smf.ols(data = df , formula = 'urban ~age+I(age**2)+IQ+married+south').fit()
model_1.params.round(3)

Intercept      16.514
I(age ** 2)     0.015
IQ             -0.000
married        -0.003
south           0.010
urban           0.014
dtype: float64

In [88]:
VIF_1 = 1/(1 - round(model_1.rsquared,3))
VIF_1.round(2)

500.0

In [89]:
VIF_2 = 1/(1 - round(model_2.rsquared,3))
VIF_2.round(2)

500.0

In [90]:
VIF_3 = 1/(1 - round(model_3.rsquared,3))
VIF_3.round(2)

1.02

# Задача 5.1, листок 8

In [91]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/wage2.csv')
df

wage  hours   IQ  KWW  educ  exper  tenure  age  married  black  south  \
0     769     40   93   35    12     11       2   31        1      0      0   
1     808     50  119   41    18     11      16   37        1      0      0   
2     825     40  108   46    14     11       9   33        1      0      0   
3     650     40   96   32    12     13       7   32        1      0      0   
4     562     40   74   27    11     14       5   34        1      0      0   
..    ...    ...  ...  ...   ...    ...     ...  ...      ...    ...    ...   
930   520     40   79   28    16      6       1   30        1      1      1   
931  1202     40  102   32    13     10       3   31        1      0      1   
932   538     45   77   22    12     12      10   28        1      1      1   
933   873     44  109   25    12     12      12   28        1      0      1   
934  1000     40  107   32    12     17      18   35        1      0      1   

     urban  sibs  brthord  meduc  feduc     lwage  
0        1     1      2.0    8.0    8.0  6.645091  
1        1     1      NaN   14.0   14.0  6.694562  
2        1     1      2.0   14.0   14.0  6.715384  
3        1     4      3.0   12.0   12.0  6.476973  
4        1    10      6.0    6.0   11.0  6.331502  
..     ...   ...      ...    ...    ...       ...  
930      0     0      1.0   11.0    NaN  6.253829  
931      1     7      7.0    8.0    6.0  7.091742  
932      0     9      NaN    7.0    NaN  6.287858  
933      0     1      1.0    NaN   11.0  6.771935  
934      0     5      1.0    NaN    NaN  6.907755  

[935 rows x 17 columns]

In [93]:
df['age_urban']=df['age']*df['urban']
df['IQ_urban']=df['IQ']*df['urban']
df

wage  hours   IQ  KWW  educ  exper  tenure  age  married  black  south  \
0     769     40   93   35    12     11       2   31        1      0      0   
1     808     50  119   41    18     11      16   37        1      0      0   
2     825     40  108   46    14     11       9   33        1      0      0   
3     650     40   96   32    12     13       7   32        1      0      0   
4     562     40   74   27    11     14       5   34        1      0      0   
..    ...    ...  ...  ...   ...    ...     ...  ...      ...    ...    ...   
930   520     40   79   28    16      6       1   30        1      1      1   
931  1202     40  102   32    13     10       3   31        1      0      1   
932   538     45   77   22    12     12      10   28        1      1      1   
933   873     44  109   25    12     12      12   28        1      0      1   
934  1000     40  107   32    12     17      18   35        1      0      1   

     urban  sibs  brthord  meduc  feduc     lwage  age_urban  IQ_urban  
0        1     1      2.0    8.0    8.0  6.645091         31        93  
1        1     1      NaN   14.0   14.0  6.694562         37       119  
2        1     1      2.0   14.0   14.0  6.715384         33       108  
3        1     4      3.0   12.0   12.0  6.476973         32        96  
4        1    10      6.0    6.0   11.0  6.331502         34        74  
..     ...   ...      ...    ...    ...       ...        ...       ...  
930      0     0      1.0   11.0    NaN  6.253829          0         0  
931      1     7      7.0    8.0    6.0  7.091742         31       102  
932      0     9      NaN    7.0    NaN  6.287858          0         0  
933      0     1      1.0    NaN   11.0  6.771935          0         0  
934      0     5      1.0    NaN    NaN  6.907755          0         0  

[935 rows x 19 columns]

In [94]:
model_1 = smf.ols(data = df , formula = 'age ~ urban+age_urban+ IQ+IQ_urban').fit()
model_2 = smf.ols(data = df , formula = 'urban ~ age+age_urban+IQ+IQ_urban').fit()
model_3 = smf.ols(data = df , formula = 'age_urban ~ age+urban+IQ+IQ_urban').fit()
model_1.params.round(3)

Intercept    33.242
urban       -33.242
age_urban     1.000
IQ           -0.001
IQ_urban      0.001
dtype: float64

In [95]:
VIF_1 = 1/(1 - round(model_1.rsquared,3))
VIF_1.round(2)

3.32

In [96]:
VIF_2 = 1/(1 - round(model_2.rsquared,3))
VIF_2.round(2)

166.67

In [97]:
VIF_3 = 1/(1 - round(model_3.rsquared,3))
VIF_3.round(2)

111.11